<?php
namespace app\index\controller;

use app\index\model\Imgs;
use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!$this->checkLogin()){
            $this->redirect('Login/index');
        }
    }

    public function checkLogin()
    {
        if(Session::has('username','global'))
            return true;
        else
            return false;
    }

}
