<?php

namespace app\index\controller;

use think\Controller;
use think\Session;

class Basic extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!$this->checkLogin()) {
            $this->redirect('Login/index');
        }
    }

    public function checkLogin()
    {
        if (Session::has('abc_username', 'global')) {
            return true;
        } else {
            return false;
        }
    }
}
