<?php

namespace app\index\controller;

use app\index\model\Imgs;
use think\Controller;

class Index extends Basic
{
    protected $imgObj;
    protected $reimg;
    protected $cakeimg;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->imgObj = new Imgs();
        $this->reimg = new ResizeImage();
        $this->cakeimg = new CakeImg();
    }

    public function index()
    {
        //获取首页图片数据
        $img_res = $this->imgObj->getIndexImgs();
        $this->assign('img_res', $img_res);

        return view('index/index');
    }

    public function getMoreImgs()
    {
        $page = !isset($_POST['page']) ? false : $_POST['page'];
        $data = $this->imgObj->getMoreImgs($page);

        return json($data);
    }

    public function getResize()
    {
        $path = 'E:\img';
        $handler = opendir($path);
        /*其中$filename = readdir($handler)是每次循环的时候将读取的文件名赋值给$filename，为了不陷于死循环，所以还要让$filename !== false。一定要用!==，因为如果某个文件名如果叫’0′，或者某些被系统认为是代表false，用!=就会停止循环*/
        while (false !== ($filename = readdir($handler))) {
            if ('.' != $filename && '..' != $filename) { //生成缩略图名
                $img_name = explode('.', $filename);
                if (isset($img_name[1])) {
                    $thumbnail = explode('.', $filename)[0] . '_re' . '.' . explode('.', $filename)[1];
                    $cake = explode('.', $filename)[0] . '_cake' . '.' . explode('.', $filename)[1];
                    $source_path = $path . '/' . $filename;
                    $img_info = getimagesize($source_path);
                    $target_width = (int)($img_info[0] / 1);
                    $target_height = (int)($img_info[1] / 1);
                    $this->reimg->resizeimage($source_path, $target_width, $target_height, 0, $path . '\thumbnail\\' . $thumbnail, 50);
                    $this->cakeImg($source_path, $path . '\cake\\' . $cake);
                    //这里简单的用echo来输出文件名
                    $str = 'http://mobparkcn-files.oss-cn-hangzhou.aliyuncs.com/gm-mp/ambercc/imgs/2017-09-28/' . $thumbnail;
                    $url = 'http://mobparkcn-files.oss-cn-hangzhou.aliyuncs.com/gm-mp/ambercc/imgs/2017-09-28/' . $filename;
                    $cake = 'http://mobparkcn-files.oss-cn-hangzhou.aliyuncs.com/gm-mp/ambercc/imgs/2017-09-28/' . $cake;
                    $sql = "INSERT INTO amb_imgs(url,thumbnail,cake) VALUES ('{$url}','{$str}','{$cake}')";
                    $num = $this->imgObj->query($sql);
                    if ($num) {
                        echo 'seccess<br>';
                    } else {
                        echo $filename . ' error<br>';
                    }
                }
            }
        }
        closedir($handler);
    }

    public function cakeImg($source, $target)
    {
        $width = 700;
        $height = 480;
        $this->cakeimg->image_center_crop($source, $width, $height, $target);
    }
}
