<?php
namespace app\index\controller;

use app\index\model\Imgs;

class Index extends Base
{
    protected $imgObj;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->imgObj=new Imgs();
    }

    public function index()
    {
        //获取首页图片数据
        $img_res=$this->imgObj->getIndexImgs();
        /*die(dump($img_res));*/
        $this->assign("img_res",$img_res);
        return view('index/index');
    }
    public function getMoreImgs(){

        $page=empty($_POST['page'])?false:$_POST['page'];
        $data=$this->imgObj->getMoreImgs($page);

        return json($data);
    }
}
